[build]
  base="client"
  functions = "netlify/functions"
  publish = "client/dist" # ili "client/build" ako koristiš React
  command = "cd client && npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200